TicketManagement/TicketManagement/Controllers/AgentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using TicketManagement.Common;
using TicketManagement.CommonData;
using TicketManagement.Concrete.CacheLibrary;
using TicketManagement.Filters;
using TicketManagement.Helpers;
using TicketManagement.Interface;
using TicketManagement.Models;
using TicketManagement.ViewModels;

namespace TicketManagement.Controllers
{
    [AuthorizeAgent]
    [AgentCheckInAttribute]
    public class AgentController : Controller
    {
        private readonly IProfile _iProfile;
        private readonly IUserMaster _userMaster;
        private readonly IPassword _password;
        readonly SessionHandler _sessionHandler = new SessionHandler();
        public AgentController(IProfile profile, IUserMaster userMaster, IPassword password)
        {
            _iProfile = profile;
            _userMaster = userMaster;
            _password = password;
        }


        public ActionResult AgentProfile()
        {
            try
            {
                var agentprofile = _iProfile.GetprofileById(Convert.ToInt64(_sessionHandler.UserId));
                return View(agentprofile);
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public ActionResult AgentProfile(UsermasterEditView usermasterEditView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result =
                        _iProfile.UpdateUserMasterDetails(Convert.ToInt64(_sessionHandler.UserId), usermasterEditView);

                    if (result != 0)
                    {
                        TempData["MessageProfileUpdate"] = CommonMessages.UserDetailsUpdateSuccessMessages;
                        return RedirectToAction("AgentProfile");
                    }
                    else
                    {
                        return View(usermasterEditView);
                    }
                }
                else
                {
                    return View(usermasterEditView);
                }
            }
            catch (Exception)
            {
                throw;
            }

        }

        [HttpPost]
        public ActionResult Profileimage(FormCollection frm)
        {

            try
            {
                foreach (string file in Request.Files)
                {
                    ProfileImage profileImage = new ProfileImage();
                    profileImage.ProfileImageId = 0;
                    string data = string.Empty;
                    var fileContent = Request.Files[file];
                    if (fileContent != null && fileContent.ContentLength > 0)
                    {
                        // and optionally write the file to disk
                        var fileName = Path.GetFileName(fileContent.FileName);
                        var fileextension = Path.GetExtension(fileContent.FileName);

                        if (fileName != null)
                        {
                            using (var fsp = fileContent.InputStream)
                            {
                                BinaryReader br = new System.IO.BinaryReader(fsp);
                                data = Convert.ToBase64String(br.ReadBytes(fileContent.ContentLength));
                            }
                        }
                    }

                    profileImage.ProfileImageBase64String = data;
                    profileImage.CreatedDate = DateTime.Now;
                    profileImage.UserId = Convert.ToInt64(_sessionHandler.UserId);
                    _iProfile.UpdateProfileImage(profileImage);

                }
            }
            catch (Exception)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json("Upload failed");
            }

            return Json("File uploaded successfully");
        }

        [HttpPost]
        public ActionResult CheckIsProfileImageExists()
        {
            try
            {
                var result = _iProfile.IsProfileImageExists(Convert.ToInt64(_sessionHandler.UserId));
                if (result)
                {
                    var imageBase64String =
                        _iProfile.GetProfileImageBase64String(Convert.ToInt64(_sessionHandler.UserId));
                    var tempimageBase64String = string.Concat("data:image/png;base64,", imageBase64String);
                    return Json(new { result = true, base64string = tempimageBase64String },
                        JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, base64string = "" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public ActionResult DeleteProfilepicture()
        {
            try
            {
                var isexists = _iProfile.IsProfileImageExists(Convert.ToInt64(_sessionHandler.UserId));
                if (isexists)
                {
                    var result = _iProfile.DeleteProfileImage(Convert.ToInt64(_sessionHandler.UserId));
                    if (result > 0)
                    {
                        return Json(new { result = true }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { result = false }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json(new { result = false }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        public ActionResult UpdateSignature(ViewSignatureRequestViewModel viewSignatureRequestViewModel)
        {
            try
            {
                if (!string.IsNullOrEmpty(viewSignatureRequestViewModel.Signature))
                {
                    if (_iProfile.CheckSignatureAlreadyExists(Convert.ToInt64(_sessionHandler.UserId)))
                    {
                        int result = _iProfile.DeleteSignature(Convert.ToInt64(_sessionHandler.UserId));

                        if (result != 0)
                        {
                            Signatures signatures = new Signatures()
                            {
                                UserId = Convert.ToInt64(_sessionHandler.UserId),
                                Signature = viewSignatureRequestViewModel.Signature,
                                SignatureId = 0
                            };

                            _iProfile.UpdateSignature(signatures);

                            return Json(true, JsonRequestBehavior.AllowGet);
                        }

                        return Json(false, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        Signatures signatures = new Signatures()
                        {
                            UserId = Convert.ToInt64(_sessionHandler.UserId),
                            Signature = viewSignatureRequestViewModel.Signature,
                            SignatureId = 0
                        };

                        _iProfile.UpdateSignature(signatures);

                        return Json(true, JsonRequestBehavior.AllowGet);
                    }
                }

                return Json(false, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {

                throw;
            }
        }

        public ActionResult GetSignature()
        {
            try
            {
                var result = _iProfile.CheckSignatureAlreadyExists(Convert.ToInt64(_sessionHandler.UserId));
                if (result)
                {
                    var signature = _iProfile.GetSignature(Convert.ToInt64(_sessionHandler.UserId));
                    return Json(new { result = true, values = signature }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { result = false, values = "" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public ActionResult Changepassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Changepassword(ChangePasswordViewModel changePasswordViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var storedUserpassword = _password.GetPasswordbyUserId(Convert.ToInt64(_sessionHandler.UserId));
                    var usersalt = _userMaster.GetUserSaltbyUserid(Convert.ToInt64(_sessionHandler.UserId));
                    var generatehash = GenerateHashSha512.Sha512(changePasswordViewModel.ExistingPassword, usersalt.PasswordSalt);

                    if (changePasswordViewModel.ExistingPassword == changePasswordViewModel.NewPassword)
                    {
                        ModelState.AddModelError("", @"New Password Cannot be same as Old Password");
                        return View(changePasswordViewModel);
                    }

                    if (!string.Equals(storedUserpassword, generatehash, StringComparison.Ordinal))
                    {
                        ModelState.AddModelError("", "Current Password Entered is InValid");
                        return View(changePasswordViewModel);
                    }

TicketManagement/TicketManagement/Views/Hod/Changepassword.cshtml
@model TicketManagement.ViewModels.ChangePasswordViewModel
@{
    ViewBag.Title = "Changepassword";
    Layout = "~/Views/Shared/_LayoutHOD.cshtml";
}

<div class="">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><i class="fa fa-cogs" style="font-size: 24px; color: #50C878"> </i> Settings </h2>

                <div class="clearfix"></div>
            </div>
            <div class="x_content">


                @using (Html.BeginForm("Changepassword", "Agent", FormMethod.Post, new { @id = "cpForm", @name = "cpForm" }))
                {
                    if (TempData["MessageChangePassword"] != null)
                    {
                        <div class="alert alert-success alert-dismissible">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>Message!</strong> @TempData["MessageChangePassword"]
                        </div>
                    }

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="tab-pane active" id="changepassword">
                        <h2>Change password</h2>
                        <hr>
                        <div class="row">
                            <div class="col-lg-4">
                                <label>Existing Password</label>
                                @Html.PasswordFor(m => m.ExistingPassword, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ExistingPassword, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <label>New Password</label>
                                @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <label>Confirm New Password</label>
                                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <br>
                            <button class="btn btn-success" id="btnsubmit" type="submit"><i class="fa fa-check-circle"></i> Save Changes</button>
                            <a href="/HODDashboard/Dashboard" class="btn btn-default"><i class="glyphicon glyphicon-repeat"></i> Cancel</a>
                        </div>
                    </div>




                }
            </div>
        </div>
    </div>
</div>
@section customscripts{
    <script src="~/Scripts/crypto/sha512.min.js"></script>

    <script type="text/javascript">

    $(document).ready(function() {
        $("#btnsubmit").click(function() {
            if ($('#NewPassword').val() != "" && $('#ConfirmPassword').val() != "" && $('#ExistingPassword').val() != "") {

                if (validatePassword($('#NewPassword').val()) == false) {
                    alert('New Password Must Have Minimum 7 characters at least 1 Alphabet, 1 Number and 1 Special Character !');
                    return false;
                } else {
                    var password = $('#NewPassword').val();
                    var passwordhash = sha512(password);

                    var confirmpassword = $('#ConfirmPassword').val();
                    var confirmpasswordhash = sha512(confirmpassword);

                    var currentpassword = $('#ExistingPassword').val();
                    var currentpasswordhash = sha512(currentpassword);

                    $('#ExistingPassword').val(currentpasswordhash);
                    $('#NewPassword').val(passwordhash);
                    $('#ConfirmPassword').val(confirmpasswordhash);
                    $("#cpForm").submit();
                }


            }


        });

        $("#NewPassword").blur(function(event) {
            if ($("#NewPassword").val() != "") {
                if (validatePassword($("#NewPassword").val()) == false) {
                    alert('New Password Must Have Minimum 7 characters at least 1 Alphabet, 1 Number and 1 Special Character !');
                    $("#NewPassword").val('');
                }

                var data = $("#NewPassword").val().length;
                if (data > 20) {
                    alert('Maximum 20 character password is Allowed!');
                    $("#NewPassword").val('');
                }
            }

        });
    });
        function validatePassword(password) {
            var reg = /^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@@$!%*#?&])[A-Za-z\d$@@$!%*#?&]{7,}$/;
            if (reg.test(password)) {
                return true;
            } else {
                return false;
            }
        }

        </script>
    }

TicketManagement/TicketManagement/Views/Hod/ProfileInformation.cshtml
@model TicketManagement.ViewModels.UsermasterEditView
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_LayoutHod.cshtml";
}


<div class="">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><i class="fa fa-cogs" style="font-size: 24px; color: #50C878"> </i> Settings </h2>
                
                <div class="clearfix"></div>
            </div>
            <div class="x_content">



                <ul class="nav nav-tabs" id="myTab">
                    <li id="li1" class="active"><a href="#settings" data-toggle="tab">Settings</a></li>
                    <li id="li2"><a href="#profileimage" data-toggle="tab">Profile Image</a></li>
                    <li id="li3"><a href="#Signature" data-toggle="tab">Signature</a></li>
                </ul>

                <div class="tab-content">
                    <!--/tab-pane-->
                    <div class="tab-pane active" id="settings">
                        @if (TempData["MessageProfileUpdate"] != null)
                    {
                            <div class="alert alert-success alert-dismissible">
                                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                <strong>Message!</strong> @TempData["MessageProfileUpdate"]
                            </div>
                    }
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @using (Html.BeginForm())
                    {
                            @Html.AntiForgeryToken()

                            <h2>My Details</h2>
                            <hr>
                            <div class="row">
                                <div class="col-lg-6">
                                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "mandatory" })
                                    @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control", @maxlength = 40, @onkeypress = "return onlyspecchar(event);" })
                                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-lg-6">
                                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "mandatory" })
                                    @Html.TextBoxFor(model => model.LastName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "mandatory" })
                                    @Html.TextBoxFor(model => model.EmailId, new { @class = "form-control", @maxlength = 50 })
                                    @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
                                </div>
                                <div class="col-lg-6">
                                    @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label" })
                                    @Html.TextBoxFor(model => model.MobileNo, new { @class = "form-control", @maxlength = "10" })
                                    @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row">
                                <div class="clearfix"></div>
                                <div class="col-lg-6" style="margin-top: 20px;">

                                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "mandatory" })
                                    @Html.RadioButtonFor(model => model.Gender, "M") @Html.Label("", "Male")
                                    @Html.RadioButtonFor(model => model.Gender, "F") @Html.Label("", "Female")
                                    <br />
                                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <br>
                                    <button class="btn btn-success" type="submit"><i class="fa fa-check-circle"></i> Save Changes</button>
                                    <a href="/HODDashboard/Dashboard" class="btn btn-default"><i class="glyphicon glyphicon-repeat"></i> Cancel</a>
                                </div>
                            </div>
                    }
                    </div>


                    <div class="tab-pane" id="profileimage">
                        <h2>Change profile image</h2>
                        <hr>
                        <div id="img_profile">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div align="left">
                                        <img alt="User Pic" src="~/Images/nobody_m.original.jpg" id="profile-image1" class="img-circle img-responsive">
                                        <br />
                                        <input id="profileimageupload_1" onchange="ValidateFile(this);" name="profileimageupload_1" class="form-control" type="file">
                                        <div class="text-danger" name="_val1" id="_val1">
                                        </div>
                                    </div>
                                    <br>
                                </div>
                            </div>
                        </div>
                        <div id="img_profile_uploaded">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div align="left">
                                        <img alt="User Pic" class="img-thumbnail" height="100px" width="200px" id="uploadedprofile">
                                    </div>
                                </div>
                                <br>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <br>
                                    <button class="btn btn-danger" id="bntDeleteProfile" name="bntDeleteProfile" type="submit"><i class="fa fa-check-circle"></i> Delete Profile Pic</button>
                                    <a href="/HODDashboard/Dashboard" class="btn btn-default"><i class="glyphicon glyphicon-repeat"></i> Cancel</a>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="tab-pane" id="Signature">
                        <h2>Signature Details</h2>
                        <hr>
                        <div class="row">
                            <div class="col-lg-6">
                                <label>Signature</label>
                                @Html.TextArea("TextSignature", new { @class = "form-control", @maxlength = "50", @onkeypress = "return this.value.length<=50" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <br>
                                <button class="btn btn-success" id="btnSignature_OK" type="submit"><i class="fa fa-check-circle"></i> Save Changes</button>
                                <a href="/HODDashboard/Dashboard" class="btn btn-default"><i class="glyphicon glyphicon-repeat"></i> Cancel</a>
                            </div>
                        </div>
                    </div>


                </div>

            </div>
        </div>

    </div>
</div>
<style>
    #profile-image1 {
        cursor: pointer;
        width: 100px;
        height: 100px;
        border: 2px solid #03b1ce;
    }

    .tital {
        font-size: 16px;
        font-weight: 500;
    }

    .bot-border {
        border-bottom: 1px #f8f8f8 solid;
        margin: 5px 0 5px 0;
    }
</style>
@section customscripts{
    <script src="~/Scripts/ValidationScript/hod.settings.js"></script>
}